### ISSUE TITLE
Check why CHEBI job is not triggered by updates on their ftp site

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#104]
This what is currently in [chebi.md](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/chebi.md)

```
build:
  source_url: http://build.berkeleybop.org/job/build-chebi/lastSuccessfulBuild/artifact/*zip*/archive.zip
  path: archive/main
  method: archive
  infallible: 1
```

The jenkins job should be triggered automatically. This is a bit more difficult for CHEBI as they use ftp rather than a VCS, so we have a script that polls, seems to be broken.
