### ISSUE TITLE
STATO has two contacts, but the schema only allows one

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/OBOFoundry.github.io#1386]
While looking for duplicate keys for #1382 @apmody discovered that `stato.md` includes two contacts:

```
contact:
  email: proccaserra@gmail.com
  label: Philippe Rocca-Serra
contact:
  email: alejandra.gonzalez.beltran@gmail.com
  label: Alejandra Gonzalez-Beltran
```

YAML does not allow duplicate keys, but PyYAML just silently uses the last key. We're trying to fix this bad behaviour. We can't just merge in this case because the schema only allows for one contact. I think there's another issue about supporting multiple contacts somewhere, but I can't find it at the moment.

To keep moving ahead with our registry clean up we'll keep the second `contact` (which is what PyYAML was doing), delete the first contact for now, and circle back to this issue.
