### ISSUE TITLE
Add a field to products schema indicating preferred version for a particular browser (e.g OLS)

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1441]
The broad problem is as follows

Most modern ontologies will reference classes in other ontologies. Usually they will *reference* a class, but sometimes they will say something *about* a class (e.g PR and HGNC; or uberon bridge axioms)

We make imports files for modules from referenced ontologies using robot/slme

It has become fairly standard to merge these imports into the default release (foo.owl), and to make basic versions (foo-basic.obo) that exclude these; as well as base files.

However, not all ontologies will make the merged file the default. this includes GO. this is because the merged file is highly confusing to 99% of users.

Additionally, in the past ad-hoc decisions have been made about different browsers loading different versions of ontologies (e.g. sometimes OLS loads a .obo if the .owl is too complex)

As a solution we should have a field in products that indicates which browsers should load which product
      -

**Comment by cmungall** [comment]
so one approach is a `default_for`

```yaml
products:
 - id: go.owl
   title: "GO (OWL edition)"
   description: "The main ontology in OWL. This is self contained and does not have connections to other OBO ontologies"
   page: http://geneontology.org/page/download-ontology
 - id: go.obo
   title: "GO (OBO Format edition)"
   description: "Equivalent to go.owl, in obo format"
   page: http://geneontology.org/page/download-ontology
 - id: go.json
   title: "GO (JSON edition)"
   description: "Equivalent to go.owl, in obograph json format"
   page: https://github.com/geneontology/obographs/
 - id: go/extensions/go-plus.owl
   title: GO-Plus
   description: "The main ontology plus axioms connecting to select external ontologies, with subsets of those ontologies"
   page: http://geneontology.org/page/download-ontology
   default_for:
      - OLS
      - Ontobee
 - id: go/go-base.owl
   title: GO Base Module
   description: "The main ontology plus axioms connecting to select external ontologies, excluding the external ontologies themselves"
   page: http://geneontology.org/page/download-ontology
```
