### ISSUE TITLE
Ontology for the Anatomy of the Insect SkeletoMuscular system (AISM)

### ISSUE THREAD

**Issue by JCGiron** [OBOFoundry/OBOFoundry.github.io#1474]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
Ontology for the Anatomy of the Insect SkeletoMuscular system

## Requested ID space
AISM

## Ontology location
https://github.com/insect-morphology/aism

## Contact person
Name: Jennifer Girón
Email address: entiminae@gmail.com
GitHub username: JCGiron

## Issue tracker
https://github.com/insect-morphology/aism/issues

## Ontology license

- [X] CC0 (public domain)
- [ ] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
owl, obo, jason

## What domain is the ontology intended to cover?
Insect anatomy

## Related OBO Foundry ontologies
CL, PATO, CARO, BSPO, RO, UBERON

## Intended use/related projects
Multispecies insect anatomy ontologies are used as bases for robust knowledge bases for specific anatomical terms (Yoder et al. 2010, HAO Portal), improve the accessibility of morphology descriptions ([Balhoff et al. 2014](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0094056)), and are useful for improving the modeling of discrete morphological characters in phylogenetic context (Tarasov [2019a](https://academic.oup.com/sysbio/article/68/5/698/5298740), [2019b](https://academic.oup.com/isd/article/3/6/1/5584145)).

There are two major reasons why insects are poorly represented amongst multispecies anatomy ontologies: lack of a base insect anatomy ontology and the lack of infrastructure to build such resource.

The ontology for the Anatomy of the Insect SkeletoMuscular system contains terms used to describe the cuticle - as a single anatomical structure - and the skeletal muscle system in insect biodiversity research. The cuticle is the product of the single layer epithelium and mirrors changes in the morphology of this single sheet (like a blanket). This ontology serves as a root ontology for other multispecies insect anatomy ontologies.
This ontology repository was created using the [Ontology Development Kit](https://github.com/INCATools/ontology-development-kit).

**Comment by zhengj2007** [comment]
Discussed on 2021-04-20 call. 

@matentzn will look at it and reply soon.

**Comment by matentzn** [comment]
Hey @JCGiron! Aside from the above comments, could you please fill in the following metadata record which will be used by the OBO Foundry website? Note that the values shown are just examples, for example something like aism, cohm, mondo (it does not have to be four letters). your_domain_like_for_example_anatomy could be simply anatomy, and the license should be whatever your actual license is. An example can be found here, but you really only need to fill in the metadata mentioned here. You can copy the below, and make a new comment with the correct information pertaining to your ontology. Thank you!

```
id: aism
title: The Title Of Your Ontology
contact:
  email: email@example.com
  label: Your Name
description: Some one sentence description of your ontology.
domain: anatomy
homepage: https://github.com/YOURORG/your_repo
products:
  - id: yourfourletterid.owl
  - id: yourfourletterid.obo
dependencies:
  - id: ro
  - id: otheroboontology
tracker: https://github.com/YOURORG/your_repo/issues
license:
  url: http://creativecommons.org/licenses/by/3.0/
  label: CC-BY
usages:
  - user: http://website.of.the.project.using.my.ontology.com
    description: A short description how the project above is using my ontology
```

**Comment by JCGiron** [comment]
Of course!
```
id: aism
title: Ontology for the Anatomy of the Insect SkeletoMuscular system
contact:
  email: entiminae@gmail.com
  label: Jennifer C. Girón
description: The AISM contains terms used in insect biodiversity research for describing structures of the exoskeleton and the skeletomuscular system. It aims to serve as the basic backbone of generalized terms to be expanded with order-specific terminology.
domain: insect anatomy
homepage: https://github.com/insect-morphology/aism
products:
  - id: aism.owl
  - id: aism.obo
dependencies:
  - id: ro
  - id: uberon
  - id: caro
  - id: pato
  - id: bfo
  - id: bspo
tracker: https://github.com/insect-morphology/aism/issues
license:
  url: https://creativecommons.org/licenses/by/4.0/
  label: CC-BY
usages:
  - user: https://github.com/insect-morphology/colao
    description: The AISM is serving as the baseline for the beetle anatomy ontology. 
  - user: https://github.com/insect-morphology/lepao
    description: The AISM is serving as the baseline for the anatomy ontology for butterflies and moths. 
```
