### ISSUE TITLE
New Ontology Request: Ontology of Process Chemistry (PROCO)

### ISSUE THREAD

**Issue by schaferw** [OBOFoundry/OBOFoundry.github.io#1487]
<a href="https://obofoundry.org/obo-nor.github.io/dashboard/proco/dashboard.html"><img src="https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2FOBOFoundry%2Fobo-nor.github.io%2Fmaster%2Fdashboard%2Fproco%2Fdashboard-qc-badge.json" /></a>

## Ontology title

Ontology of Process Chemistry

## Requested ID space

OPC

## Ontology location

https://github.com/OPC-ontology/OPC

## Contact person
Name: schaferw
Email address: wes_schafer@merck.com
GitHub username: schaferw 

Name: Oliver He
Email address: yongqunh@med.umich.edu
GitHub username: yongqunh

## Issue tracker

https://github.com/OPC-ontology/OPC/issues

## Ontology license

- [ ] CC0 (public domain)
- [ X] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats

Owl/rdf xml

## What domain is the ontology intended to cover?

Process chemistry is a branch of chemistry (including pharmaceutical chemistry) that studies the development and optimization of the production processes for chemical compounds, and the scaling up of laboratory chemical reactions into commercial routes.  Key considerations are product quality, economics, environmental sustainability, regulatory compliance and safety.  

The initial focus was small molecule development in the pharmaceutical industry but care was taken to leave it extensible to large molecules and other chemical industries.  

## Related OBO Foundry ontologies

An extensive survey of published sources found no ontology dedicated to this domain and several major gaps around defined terminology key to process chemistry.  Example gaps include regulatory terms, solid phase characterization, and safety.

Its domain borders several ontologies in the OBO foundry and OPC endeavors to make its terms as interoperable as possible with related OBO ontologies.  BFO was used as the top level ontology.  RO was used for object properties.  The Chemical Method Ontology (CHMO) contains more than 3000 classes and describes methods used to collect data, prepare and analyze samples. The analytical methods defined in CHMO are classified in method-families, and described and equipped with synonyms. Many of the unit operations associated with sample preparation could be leveraged in the synthetic chemistry space.  They are imported but sub-classed as unit operations in the synthetic chemist / chemical engineer vernacular. The RXNO is by far the most complete reaction ontology, which contains more than 500 classes representing organic reaction types (https://www.ebi.ac.uk/ols/ontologies/rxno).  It does not provide concepts to describe the metadata around individual experiments.  The ontology was specifically developed to provide experimental contextual metadata to the results and methods already described by CHMO and Allotrope (AFO).

Terms from other OBO ontologies such as CheBI, CHEMINF, OBI, PATO and SBO have been imported when appropriate.

## Intended use/related projects

The ontology was developed with the use-case of structuring and standardizing terminology used in process chemistry workflows.  Examples include templating experiments in electronic notebooks and batch records as well as and standardizing terminology in documents in enterprise document management systems to maximize capabilities in data mining and machine learning applications.  The ontology will be used as a basis for developing graph based data storage and enabling semantic reasoning in data queries which would allow query engines to infer logical consequences from a set of asserted facts or axioms defined in the ontology which can identify data not found in ordinary searches.

Future use cases could include standardizing and automating initial drafts of internal documentation and regulatory filings,  translation of manual experiments to recipes used by automated reactors, and
journal articles especially addendum information.

Presented at Allotrope Connect conference.  A manuscript is in-progress.

## Data source

https://github.com/OPC-ontology/OPC/blob/master/src/ontology/opc-base.owl
with merged / imported terms:
https://github.com/OPC-ontology/OPC/blob/master/src/ontology/opc.owl

## Additional comments or remarks

We have followed OBO development principles.

**Comment by zhengj2007** [comment]
Discussed on the call 2021-04-20.

The domain is appropriate. Need to check whether CHMO is still active. 

Ran Dashboard to check whether the ontology follows the OBO Foundry principles. 
https://obofoundry.github.io/obo-nor.github.io/dashboard/index.html

Since the ontology has not been registered, Dashboard cannot check the ontology metadata, e.g domain, usage. Please just use the dashboard results as reference to fix the issues in the ontology file if possible.

**Comment by cmungall** [comment]
Some general comments. These comments are distinct from evaluation of criteria for inclusion in OBO

 - it looks like you are using the Allotrope upper ontology. I think we should explore whether shadow terms should be added to COB. I would welcome a broader conversion at the OBO-Allotrope level here
 - it looks like in some cases STATO is used but the STATO ID is replace by an OPC ID?

**Comment by matentzn** [comment]
Hey @schaferw ! Aside from the above comments, could you please fill in the following metadata record which will be used by the OBO Foundry website? Note that the values shown are just examples, for example yourfourletterid could be something like aism, cohm, mondo (it does not have to be four letters). your_domain_like_for_example_anatomy could be simply anatomy, and the license should be whatever your actual license is. An example can be found here, but you really only need to fill in the metadata mentioned here. You can copy the below, and make a new comment with the correct information pertaining to your ontology. Thank you!

```
id: opc
title: Ontology of Process Chemistry
contact:
  email: email@example.com
  label: Your Name
description: Some one sentence description of your ontology.
domain: anatomy
homepage: https://github.com/YOURORG/your_repo
products:
  - id: yourfourletterid.owl
  - id: yourfourletterid.obo
dependencies:
  - id: ro
  - id: otheroboontology
tracker: https://github.com/YOURORG/your_repo/issues
license:
  url: http://creativecommons.org/licenses/by/3.0/
  label: CC-BY
usages:
  - user: http://website.of.the.project.using.my.ontology.com
    description: A short description how the project above is using my ontology
```

**Comment by yongqunh** [comment]
@zhengj2007 I am gald that the domain to be covered by the OPC (Ontology of Process Chemistry) is considered as appropriate. Funded by a Merck grant, I have been working with Wes Schafer from Merck and other collaborators since two years ago on this project. We also presented a talk about the research in last year's Allotrope meeting:
https://a931b97a-f419-4166-9ec6-4bd98cdfcfa7.filesusr.com/ugd/b6aabf_e139357058f84b5b9b80dedf6111f50b.pdf

@cmungall Yes. Both Wes and I have been proposing to Allotrope to collaborate with OBO and possibly join the OBO as well. The Allotrope ontologies (https://www.allotrope.org/ontologies) are indeed aligned with BFO, open, and encourage collaboration. 

@zhengj2007 @cmungall @matentzn : Wes and I have discussed today, and we will address the specific comments raised by you later and soon. Thanks a lot!     

Note that we will present a OPC talk at 10 am EST tomorrow (April 22, 2021) in this year's Allotrope annual meeting:
https://www.allotrope.org/2021-spring-allotrope-connect
Our presentation title is: 
"Ontology for Process Chemistry – Giving Context to Instrument Data Structured by the Allotrope Data Model"
Everyone is welcome to attend!

**Comment by schaferw** [comment]
@matentzn  Here is the requested information.

id: opc
title: Ontology of Process Chemistry
contact: 
  email: wes_schafer@merck.com
  label: Wes Schafer
  email: yongqunh@med.umich.edu
  label: Oliver He
description: OPC covers process chemistry, the chemical field concerned with scaling up laboratory syntheses to commercially viable processes. 
domain: process chemistry
homepage: https://github.com/OPC-ontology/OPC
products:
  - id: opc.owl
  - id: opc.obo
dependencies:
  - id: ro
  - id: obi
  - id: CheBI
  - id: PATO
  - id: CHEMINF
  - id: SBO
tracker: https://github.com/OPC-ontology/OPC/issues
license:
  url:  http://creativecommons.org/licenses/by/4.0/
  label: CC-BY
usages:
  - user: Merck & Co.
  - description: pharmaceutical API development
  - user: Allotrope
  - description: important domain in pharmaceutical industry,

**Comment by matentzn** [comment]
@schaferw great, thank you very much!

Before we do our content review, we would like to invite you to make sure that your ontology passes the minimum QC threshold (or provide reasons why you don't want to / cannot):

https://obofoundry.github.io/obo-nor.github.io/dashboard/index.html

In the ideal world (that @yongqunh is also helping us craft) we would like all ontologies to pass that minimum threshold, at least to the extent that there are no `ERROR`s. 

You can find the reports specific to OPC here:
https://obofoundry.github.io/obo-nor.github.io/dashboard/opc/dashboard.html

So as far as I can see, to pass, you basically just need to fix one definition, and add a version IRI!

Let me know when that is done (of if you don't want to do it), and we will commence with the review.

**Comment by zhengj2007** [comment]
Discussed on June 29, 2021 call.

@pbuttigieg will review the ontology.

**Comment by pbuttigieg** [comment]
Hi all, looking at the latest file in your src/ directory, I note several issues:

1. The ELK reasoner generates multiple unsatisfiable classes (as detected in the dashboard)
![image](https://user-images.githubusercontent.com/2276146/123843193-eb487d80-d911-11eb-91ea-e0fb1de4d689.png)


2. There seem to be many orphaned and unlabelled terms imported:
![image](https://user-images.githubusercontent.com/2276146/123843291-0b783c80-d912-11eb-97f8-daee8e1376c6.png)

3. Some definitions seem incomplete, and the term editors would be better as ORCIDs or similar
![image](https://user-images.githubusercontent.com/2276146/123843418-2cd92880-d912-11eb-8da6-eee5fb03ab69.png)

4. Some subclasses don't really fit - for example, under plan spec, there are records and designs, neither of which are really plans. The definitions are unclear:
![image](https://user-images.githubusercontent.com/2276146/123843554-52fec880-d912-11eb-9457-390009a0eead.png)


5. There are numerous typos, grammatical errors, and similar issues with definitions, for example: 
![image](https://user-images.githubusercontent.com/2276146/123843785-8fcabf80-d912-11eb-95d6-a0138b3f10ff.png)

On that example, I'm not clear on how a quality spec is directive in the way intended by directive information entity. 

6. It's not really good form to cite one's own ontology as a definition source



Let's start with these and work into the more fine-grained ones afterwards

7.

**Comment by yongqunh** [comment]
Good comments! I will bring these to the ontology meeting and developers for discussion. Thanks, Pier!

**Comment by lschriml** [comment]
@yongqunh -- Can you share here an update on the progress ?

Cheers,
Lynn

**Comment by yongqunh** [comment]
Hi Lynn,
Thanks for asking.
Yes. The Ontology of Process Chemistry has been updated a lot. 
Here I would like to provide a quick summary:

First of all, we have updated the id from OPC to PROCO.
PROCO: Ontology of Process Chemistry.
the id change is to avoid a conflict with another term also abbreviated as OPC. 
  
The website has been changed to: 
https://github.com/proco-ontology/PROCO

Also, the homepage has been changed to: 
https://github.com/OPC-ontology/OPC

The source has been changed to: 
https://raw.githubusercontent.com/proco-ontology/PROCO/main/src/ontology/proco.owl

Overall, the PROCO source has been significantly updated to address the comments provided earlier. 

More work is undergoing. 
@schaferw Wes may provide more information.

Best, Oliver He

**Comment by matentzn** [comment]
@yongqunh 

This is the current metadata record for PROCO:

```
- id: proco
      title: PROCO: Ontology of Process Chemistry
      mirror_from: "https://raw.githubusercontent.com/proco-ontology/PROCO/main/src/ontology/proco.owl"
      contact:
        email: wes_schafer@merck.com
        label: Wes Schafer
      description: OPC covers process chemistry, the chemical field concerned with scaling up laboratory syntheses to commercially viable processes.
      domain: process chemistry
      homepage: https://github.com/proco-ontology/PROCO
      products:
        - id: proco.owl
        - id: proco.obo
      dependencies:
        - id: ro
        - id: obi
        - id: chebi
        - id: pato
        - id: cheminf
        - id: sbo
      tracker: https://github.com/proco-ontology/PROCO/issues
      license:
        url: https://creativecommons.org/licenses/by/4.0/
        label: CC BY 4.0
      usages:
        - user: Merck & Co.
          description: pharmaceutical API development
        - user: Allotrope
          description: important domain in pharmaceutical industry
```

- [ ] If this ontology gets accepted, use the above metadata record.

We have updated your [OBO Dashboard record](https://obofoundry.github.io/obo-nor.github.io/dashboard/proco/dashboard.html). Please:

- [ ] Add a license property into the ontology
- [ ] Consider changing your Version IRI to the [recommended format](http://obofoundry.org/principles/fp-004-versioning.html)

Please let us know when these are done - as passing the dashboard is now mandatory for new ontology requests, not implementing these my result in delays of the review.

**Comment by yongqunh** [comment]
Hi Nico,

Thanks for providing the information.
We will do as instructed.

Best,
Oliver

**Comment by matentzn** [comment]
@yongqunh problem persists: 

https://obofoundry.org/obo-nor.github.io/dashboard/index.html

please let us know when they are dealt with.

**Comment by cmungall** [comment]
None of my comments are blockers to including in OBO, and I think they reflect more on the fact we need to give more guidance to ontology developers in OBO

## PROCO includes many terms that are more general than the ontology

```yaml
id: PROCO:0000003
name: prior art

id: PROCO:0000004
name: design space

id: PROCO:0000005
name: factor

id: PROCO:0000006
name: equation

...

id: PROCO:0000293
name: calculation

id: PROCO:0000294
name: calculated datum


...etc
```

Many existing ontologies in OBO do this, so there is a precedent for this and this should count as a blocker to OBO inclusion. But I implore all of us to do what we can to avoid this practice.



At a minimum I strongly urge you to have an issue in the PROCO repo addressing this, and linked issues to term requests for other ontologies.

## Logic issues

The issues @pbuttigieg brought up seem to have been fixed, thanks, but I note some cryptic incoherencies

e.g. bulk substance quality is a subclass of quality and ICE. Is this deliberate? You use a name that is consistent with PATO qualities but your intention seems to be to shadow a quality with an ICE. You can't be blamed for this as OBO practice is poor here, but I think if you really want to model it as an ICE, call it "bulk substance quality datum" or something

(the practice of shadowing characteristics with ICEs is bad but I have not yet convinced everyone in OBO of this)

## Freeform mixing of ontologies

Again, this reflects more on OBO and the fact we have not progressed as far with COB as is ideal

The ontology has things like:

```yaml
id: http://purl.allotrope.org/ontologies/material#AFM_0001097
name: chemical substance
is_a: CHMO:0000993 ! portion of material

id: CHMO:0000993 
name: portion of material
def: "An independent material continuant that is self-connected and retains its identity over time." []
is_a: BFO:0000040 ! material entity
```

here we have a class "chemical substance" combing from Allotrope (which is a good upper ontology, but different than what everyone in OBO is using), and I don't know why CHMO (which is restricted to chemical methods) is claiming a term as generic as "portion of material"

Ideally you would request terms like "chemical substance" from COB (which may recommend a CHEBI ID), and build out your ontology from COB-sanctioned terms.

See: https://obofoundry.org/COB/using-cob/

Apologies the docs are not yet as clear as we would like

As I say many of these issues are prevalent in OBO, so this should not be considered a blocker (I am OK with PROCO being added to OBO). However, I think it's really important to fix these at the early stage. Otherwise another ontology will come after this and start using PROCO IDs for "equation" and ending up importing allotrope, and it all makes it harder to harmonize across ontologies.
