### ISSUE TITLE
New Ontology: Epilepsy Ontology 

### ISSUE THREAD

**Issue by phwegner** [OBOFoundry/OBOFoundry.github.io#1514]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
Epilepsy Ontology

## Requested ID space
EPSO

## Ontology location
https://github.com/phwegner/Epilepsyontology

## Contact person
Name: Philipp Wegner, Alpha Tom Kodamullil
Email address: philipp.wegner@scai.fraunhofer.de, alpha.tom.kodamullil@scai.fraunhofer.de
GitHub username: phwegner, akodamullil

## Issue tracker
https://github.com/phwegner/Epilepsyontology/issues

## Ontology license

- [ ] CC0 (public domain)
- [X] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
.owl

## What domain is the ontology intended to cover?
Epilepsy disease

## Related OBO Foundry ontologies
DOID

## Intended use/related projects
Classification of types of Epilepsy, Textmining in Epilepsy research, Annotation of medical texts

## Data source
Parts of that is taken from previous work done by Fraunhofer SCAI and the (Epilepsy and Seizure Ontology)[https://bioportal.bioontology.org/ontologies/EPSO]

## Additional comments or remarks
Created by the team for applied semantics at Fraunhofer SCAI in cooperation with Dr. Satya Sahoo (Case Western Reserve University)

## Metadata

Please fill in the following metadata record which will be used by the OBO Foundry website. Note that the values shown are just examples, for example `yourfourletterid` could be something like `aism`, `cohm`, `mondo` (it does not have to be four letters). `your_domain_like_for_example_anatomy` could be simply `anatomy`, and the license should be whatever your actual license is. An example can be found [here](https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/amphx.md), but you really only need to fill in the metadata mentioned here.

```
id: EPSO
title: Epilepsy Eontology
contact:
  email: philipp.wegner@scai.fraunhofer.de
  label: Philipp Wegner
description: Ontology for Epilepsy disease
domain: epilepsy
homepage: https://github.com/phwegner/Epilepsyontology
products:
  - id: EPSO.owl
  - id: EPSO_merged.owl
dependencies:
  - id: 
  - id: 
tracker: https://github.com/phwegner/Epilepsyontology/issues
license:
  url: http://creativecommons.org/licenses/by/4.0/
  label: CC-BY
usages:
  - user: https://github.com/phwegner/Epilepsyontology
    description: See development section
```
