### ISSUE TITLE
Provide a generic github action that create a merged OWL version of an edit file.

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBOFoundry.github.io#1577]
There are still a a number of ontologies which have hugely outdated OWL ontology versions:
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1446

@balhoff suggests to provide a generic GitHub action for these with some instructions on how to add.

**Comment by matentzn** [comment]
@balhoff 

Something like this?

```
name: OWL release file

on:
  push:
    branches: [ master ]
    paths:
      - 'src/ontology/myontology.obo'
  
  workflow_dispatch:

jobs:
  merge_template:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: ${{ github.head_ref }}
      - name: Create OWL version
        run: cd src/ontology && robot merge --catalog catalog-v001.xml -i myontology.obo  convert --check false -f obo -o ../../myontology.obo
      - name: Create OWL version
        run: cd src/ontology && robot merge --catalog catalog-v001.xml -i myontology.obo  convert --check false -f owl -o ../../myontology.owl
      - name: Commit files
        run: |
          git add src/ontology/ro-edit.owl
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Creating OBO and OWL release files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ GitHub.head_ref }}
```
