### ISSUE TITLE
Cell Behavior Ontology (CBO)

### ISSUE THREAD

**Issue by jpsluka** [OBOFoundry/OBOFoundry.github.io#1603]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
Cell Behavior Ontology

## Requested ID space
CBO

## Ontology location
https://cbo.biocomplexity.indiana.edu/
Most recent version always located at http://cbo.biocomplexity.indiana.edu/svn/cbo/trunk/CBO.owl 
Most recent version also available (since 2012) at https://bioportal.bioontology.org/ontologies/CBO

## Contact person
Name: James Sluka
Email address: jsluka@iu.edu
GitHub username: jpsluka

## Ontology license

- [X] CC0 (public domain)
- [ ] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
OWL (CBO is an OWL-2 ontology developed in Protégé 4)

## What domain is the ontology intended to cover?
The Cell Behavior Ontology (CBO) is designed to describe multi-cell computational models. In particular to describe both the existential behaviors of cells (spatiality, growth, movement, adhesion, death, ...) and computational models of those behaviors.

## Intended use/related projects
The Cell Behavior Ontology (CBO) provides a basis for describing the spatial and observable behaviors of cells and extracellular components suitable for describing in vivo, in vitro and in silico multicell systems.

## Additional comments or remarks
The CBO has been available in BioPortal since 2012. 
The CBO is described in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4133580/

## OBO Foundry pre-registration checklist

To be considered for inclusion in the OBO Foundry, an ontology must meet certain requirements, as described in in [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration review checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md). To ensure you are aware of some of its key points, please review the checklist below.

You can either check a box by submitted the request first and then using the GitHub interface, or replacing the `- [ ]` by `- [X]` in the following.

- [X] I have read an understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md) 
- [X] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there was, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [X] My ontology has a specific release file with a version IRI and a dc:license annotation, serialised in RDF/XML.
- [X] I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, using the [IAO:0000115](http://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [X] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [X] For all relationship properties (Object and Data Property) I checked whether [RO](http://www.ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [X] For the selection of appropriate annotation properties, I looked at [OMO](http://www.ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies. 
- [X] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice.

## Metadata

Please fill in the following metadata record which will be used by the OBO Foundry website. Note that the values shown are just examples, for example `yourfourletterid` could be something like `aism`, `cohm`, `mondo` (it does not have to be four letters). `your_domain_like_for_example_anatomy` could be simply `anatomy`, and the license should be whatever your actual license is. An example can be found [here](https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/amphx.md), but you really only need to fill in the metadata mentioned here.

```
id: CBO
title: The Cell Behavior Ontology
contact:
  email: jsluka@iu.edu
  label: James Sluka
description: The Cell Behavior Ontology (CBO) is designed to describe multi-cell computational models. In particular to describe both the existential behaviors of cells (spatiality, growth, movement, adhesion, death, ...) and computational models of those behaviors.
domain: Multicell modeling
homepage: https://cbo.biocomplexity.indiana.edu/
products:
  - id: CBO.owl
  - id: CBO.obo
dependencies:
  - id: ro
  - id: 
tracker: https://cbo.biocomplexity.indiana.edu/Request%20New%20Term
license:
  url: http://creativecommons.org/licenses/by/3.0/
  label: CC-BY
usages:
  - user: 
    description: 
```
