### ISSUE TITLE
New Ontology Request: Coleoptera Anatomy Ontology (COLAO)

### ISSUE THREAD

**Issue by JCGiron** [OBOFoundry/OBOFoundry.github.io#1665]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
Coleoptera Anatomy Ontology

## Requested ID space
COLAO

## Ontology location
https://github.com/insect-morphology/colao

## Contact person
Name: Jennifer C. Girón
Email address: entiminae@gmail.com
GitHub username: JCGiron

## Issue tracker
https://github.com/insect-morphology/colao/issues

## Ontology license

- [ ] CC0 (public domain)
- [X] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
owl, obo

## What domain is the ontology intended to cover?
Insect anatomy, specifically beetles

## Related OBO Foundry ontologies
AISM, CL, PATO, CARO, BSPO, RO, UBERON

## Intended use/related projects
We intend to use this ontology for describing beetle phenotypes, expanding towards data mining applications that can eventually inform data matrices and partition schemes for phylogenetic analyses.

## Data source
This ontology includes beetle-specific anatomical terms, with terms and definitions extracted primarily from Lawrence J, Ślipiński A (2013) Adult morphology. In: Australian beetles volume 1: morphology, classification and keys. CSIRO Publishing, 30–63. https://www.publish.csiro.au/book/6466/.

## Additional comments or remarks
The backbone of COLAO is a simplified version of AISM. If needed, see here how we obtained that simplified version: https://github.com/insect-morphology/Manual/blob/main/Sections/Creating-AISM-based-insect-ontology.md#setup-aism-based-ontology-imports.

## OBO Foundry pre-registration checklist

To be considered for inclusion in the OBO Foundry, an ontology must meet certain requirements, as described in in [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration review checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md). To ensure you are aware of some of its key points, please review the checklist below.

You can either check a box by submitted the request first and then using the GitHub interface, or replacing the `- [ ]` by `- [X]` in the following.

- [X] I have read an understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md) 
- [X] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there was, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [X] My ontology has a specific release file with a version IRI and a dc:license annotation, serialised in RDF/XML.
- [X] I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, using the [IAO:0000115](http://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [X] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [X] For all relationship properties (Object and Data Property) I checked whether [RO](http://www.ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [X] For the selection of appropriate annotation properties, I looked at [OMO](http://www.ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies. 
- [X] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice.

## Metadata

Please fill in the following metadata record which will be used by the OBO Foundry website. Note that the values shown are just examples, for example `yourfourletterid` could be something like `aism`, `cohm`, `mondo` (it does not have to be four letters). `your_domain_like_for_example_anatomy` could be simply `anatomy`, and the license should be whatever your actual license is. An example can be found [here](https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/amphx.md), but you really only need to fill in the metadata mentioned here.

```
id: COLAO
title: Coleoptera Anatomy Ontology
contact:
  email: entiminae@gmail.com
  label: Jennifer C. Girón
description: The Coleoptera Anatomy Ontology contains terms used for describing the anatomy and phenotype of beetles in biodiversity research.
domain: insect anatomy
homepage: https://github.com/insect-morphology/colao
products:
  - id: colao.owl
  - id: colao.obo
dependencies:
  - id: aism
  - id: ro
  - id: uberon
  - id: caro
  - id: pato
  - id: bfo
  - id: bspo
tracker: https://github.com/insect-morphology/colao/issues
license:
  url: https://creativecommons.org/licenses/by/4.0/
  label: CC-BY
usages:
  - user: there are no current uses of this ontology besides manuscripts in preparation.
    description: We are using this ontology to describe beetle phenotypes using Phenoscript (https://github.com/sergeitarasov/PhenoScript/wiki)
```

**Comment by matentzn** [comment]
@JCGiron, Thank you very much for your submission!

The [initial dashboard check](https://obofoundry.github.io/obo-nor.github.io/dashboard/index.html) looks good. 

> there are no current uses of this ontology besides manuscripts in preparation.

We will discuss this during our next OBO Foundry committee call before assigning a reviewer.

**Comment by cmungall** [comment]
In 2011 Nico Franz submitted a beetle anatomy ontology - does anyone recall what came of that @balhoff @dosumis?

**Comment by JCGiron** [comment]
As far as I know Nico Franz started building that ontology in MX (the same online platform used for the Hymenoptera Anatomy Ontology). Active development stopped and was resumed by @entoaaron. Since MX is no longer maintained, we decided to start from scratch using the ODK and the backbone provided by [AISM](https://github.com/insect-morphology/aism). I can still check if there is an owl file available of Nico Franz's submission.
Tagging @mjy to see if he has additional information and a way to get that owl file.

**Comment by cmungall** [comment]
I see no major issues with this. I made issues in the tracker but these are non blocking for submission to OBO. Also coordinating on slack

**Comment by mjy** [comment]
@JCGiron has access to the mx file.  From what i recall/can see in mx there was no OWL version released?

**Comment by JCGiron** [comment]
@mjy is there a way to download an OWL version from what is there?

**Comment by mjy** [comment]
@JCGiron I will check.  We had a 2 step process, i.e. things were staged, worked on for a while, then assigned identifiers.  If the terms were not assigned identifiers, then they would not be OWLable.  I suspect the project was only in the pre-staging stage.  @balhoff wrote the scripts to translate to OWL, and IIRC we only have the modified versions of them for the HAO and OARCS, so I think no OWL was ever produced.  But I will try and double-check.

**Comment by matentzn** [comment]
# Next steps:

1. Make a pull request like this one to add your metadata: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1673/files
2. Create a purl config like https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/aism.yml

```
id: colao
mirror_from: https://raw.githubusercontent.com/insect-morphology/colao/master/colao.owl
title: Coleoptera Anatomy Ontology
contact:
  email: entiminae@gmail.com
  label: Jennifer C. Girón
description: The Coleoptera Anatomy Ontology contains terms used for describing the anatomy and phenotype of beetles in biodiversity research.
domain: insect anatomy
homepage: https://github.com/insect-morphology/colao
products:
  - id: colao.owl
  - id: colao.obo
dependencies:
  - id: aism
  - id: ro
  - id: uberon
  - id: caro
  - id: pato
  - id: bfo
  - id: bspo
tracker: https://github.com/insect-morphology/colao/issues
license:
  url: https://creativecommons.org/licenses/by/4.0/
  label: CC BY 4.0
```
