### ISSUE TITLE
New Ontology: Lepidoptera Anatomy Ontology

### ISSUE THREAD

**Issue by luis-gonzalez-m** [OBOFoundry/OBOFoundry.github.io#1669]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
Lepidoptera Anatomy Ontology

## Requested ID space
LEPAO

## Ontology location
https://github.com/insect-morphology/lepao

## Contact person
Name: Luis Antonio González Montaña
Email address: lagonzalezmo@unal.edu.co
                        luis.gonzalez.montana@unillanos.edu.co
GitHub username: luis-gonzalez-m

## Issue tracker
https://github.com/insect-morphology/lepao/issues

## Ontology license

- [ ] CC0 (public domain)
- [X ] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
OWL, OBO, json

## What domain is the ontology intended to cover?
Insect Anatomy

## Related OBO Foundry ontologies
AISM, CL, PATO, CARO, BSPO, RO, UBERON

## Intended use/related projects
We intend to use this ontology for describing beetle phenotypes, expanding towards data mining applications that can eventually inform data matrices and partition schemes for phylogenetic analyses.

## Data source
This ontology includes butterflies and moths-specific anatomical terms, with terms and definitions extracted primarily from 
Seifert G (1995) Entomologisches Praktikum. 3. Auflage. G. Thieme Verlag, Stuttgart, New York: 332 pp. and Kristensen, N. P., & Simonsen, T. J. (1999). Handbook of Zoology, Lepidoptera, Moths and Butterflies, 2: Morphology Physiology, and Development.

## OBO Foundry pre-registration checklist

To be considered for inclusion in the OBO Foundry, an ontology must meet certain requirements, as described in in [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration review checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md). To ensure you are aware of some of its key points, please review the checklist below.

You can either check a box by submitted the request first and then using the GitHub interface, or replacing the `- [ ]` by `- [X]` in the following.

- [X ] I have read an understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md) 
- [ X] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there was, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [X ] My ontology has a specific release file with a version IRI and a dc:license annotation, serialised in RDF/XML.
- [ X] I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, using the [IAO:0000115](http://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [X ] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [X ] For all relationship properties (Object and Data Property) I checked whether [RO](http://www.ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [X] For the selection of appropriate annotation properties, I looked at [OMO](http://www.ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies. 
- [X] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice.

## Metadata

Please fill in the following metadata record which will be used by the OBO Foundry website. Note that the values shown are just examples, for example `yourfourletterid` could be something like `aism`, `cohm`, `mondo` (it does not have to be four letters). `your_domain_like_for_example_anatomy` could be simply `anatomy`, and the license should be whatever your actual license is. An example can be found [here](https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/amphx.md), but you really only need to fill in the metadata mentioned here.

```
id: LEPAO
title: Lepidoptera Anatomy Ontology
contact:
  email: lagonzalezmo@unal.edu.co; luis.gonzalez.montana@unillanos.edu.co
  label: Luis A. González-Montaña
description: The Lepidoptera Anatomy Ontology contains terms used for describing the anatomy and phenotype of moths and butterflies in biodiversity research. LEPAO is developed in part by BIOfid (The Specialised Information Service Biodiversity Research).
domain: Insect Anatomy
homepage: https://github.com/insect-morphology/lepao
products:
  - id: lepao.owl
  - id: lepao.obo
dependencies:
  - id: aism
  - id: ro
  - id: uberon
  - id: caro
  - id: pato
  - id: bfo
  - id: bspo
tracker: https://github.com/insect-morphology/lepao/issues
license:
  url: http://creativecommons.org/licenses/by/4.0/
  label: CC-BY
usages:
  - user: there are no current uses of this ontology besides manuscripts in preparation.
    description: We are using this ontology to describe phenotypes of butterflies and moths. 
```

**Comment by matentzn** [comment]
@luis-gonzalez-m, Thank you very much for your submission!

The [initial dashboard check](https://obofoundry.github.io/obo-nor.github.io/dashboard/index.html) looks good. 

> there are no current uses of this ontology besides manuscripts in preparation.

We will discuss this during our next OBO Foundry committee call before assigning a reviewer.

**Comment by cmungall** [comment]
I see no major issues with this. I made issues in the tracker but these are non blocking for submission to OBO

**Comment by zhengj2007** [comment]
Discussed on 12-14-2021 call. Approved to add to OBO.

**Comment by matentzn** [comment]
# Next steps:

1. Make a pull request like this one to add your metadata: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1673/files
2. Create a purl config like https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/aism.yml


```
id: lepao
mirror_from: https://raw.githubusercontent.com/insect-morphology/lepao/main/lepao.owl
title: Lepidoptera Anatomy Ontology
contact:
  email: lagonzalezmo@unal.edu.co; luis.gonzalez.montana@unillanos.edu.co
  label: Luis A. González-Montaña
description: The Lepidoptera Anatomy Ontology contains terms used for describing the anatomy and phenotype of moths and butterflies in biodiversity research. LEPAO is developed in part by BIOfid (The Specialised Information Service Biodiversity Research).
domain: Insect Anatomy
homepage: https://github.com/insect-morphology/lepao
products:
  - id: lepao.owl
  - id: lepao.obo
dependencies:
  - id: aism
  - id: ro
  - id: uberon
  - id: caro
  - id: pato
  - id: bfo
  - id: bspo
tracker: https://github.com/insect-morphology/lepao/issues
license:
  url: https://creativecommons.org/licenses/by/4.0/
  label: CC BY 4.0
```
