### ISSUE TITLE
Add clearer citation/publications metadata 

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#1671]
We have the ability to add publications as metadata:

```yaml
publications:
  - id: http://www.ncbi.nlm.nih.gov/pubmed/22293552
    title: "Uberon, an integrative multi-species anatomy ontology"
  - id: http://www.ncbi.nlm.nih.gov/pubmed/25009735
    title: "Unification of multi-species vertebrate anatomy ontologies for comparative biology in Uberon"
```

http://obofoundry.org/ontology/uberon

this shows up under "cite":

Cite
Uberon, an integrative multi-species anatomy ontology
Unification of multi-species vertebrate anatomy ontologies for comparative biology in Uberon

Is a citation link the same as a publication link? If someone has a zenodo DOI for their github repo can/should they put this under "publication"

I think we need more guidance here, especially for ontologies with no peer-reviewed publication

 - do we recommend the use of zenodo archiving of the github repo, and putting the doi in the pubs field?
 - do are also recommend a github CFF field? https://github.com/INCATools/ontology-development-kit/issues/501
 - are these complementary?
