### ISSUE TITLE
New Ontology Request: Provisional Cell Ontology

### ISSUE THREAD

**Issue by shawntanzk** [OBOFoundry/OBOFoundry.github.io#1708]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
Provisional Cell Ontology

## Requested ID space
pcl

## Ontology location
https://github.com/obophenotype/provisional_cell_ontology

## Contact person
Name: David Osumi-Sutherland
Email address: davidos@ebi.ac.uk
GitHub username: dosumis

Name: Richard Scheuermann
Email address: rscheuermann@jcvi.org
GitHub username: scheuerm

## Issue tracker
https://github.com/obophenotype/provisional_cell_ontology/issues

## Ontology license

- [ ] CC0 (public domain)
- [x] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
owl
obo
json

## What domain is the ontology intended to cover?
Cell types that are provisionally defined by experimental techniques such as single cell or single nucleus transcriptomics rather than a straightforward & coherent set of properties.  All terms subclass to conventionally defined terms in CL. If more data emerges that allows more conventional definitions, terms may migrate to CL.

## Related OBO Foundry ontologies
Cell Ontology

## Intended use/related projects
Annotations for single cell transcriptomics projects. 
Search and navigation of single cell transcriptomics data explorer (see DOI:10.1101/2021.10.10.463703)

## Data source
Single Cell/Nucleus Transcriptomics experiments.

## OBO Foundry pre-registration checklist

To be considered for inclusion in the OBO Foundry, an ontology must meet certain requirements, as described in in [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration review checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md). To ensure you are aware of some of its key points, please review the checklist below.

You can either check a box by submitted the request first and then using the GitHub interface, or replacing the `- [ ]` by `- [X]` in the following.

- [X] I have read an understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md) 
- [X] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there was, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [X] My ontology has a specific release file with a version IRI and a dc:license annotation, serialised in RDF/XML.
- [X] I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, using the [IAO:0000115](http://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [X] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [X] For all relationship properties (Object and Data Property) I checked whether [RO](http://www.ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [X] For the selection of appropriate annotation properties, I looked at [OMO](http://www.ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies. 
- [X] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice.

## Metadata

Please fill in the following metadata record which will be used by the OBO Foundry website. Note that the values shown are just examples, for example `yourfourletterid` could be something like `aism`, `cohm`, `mondo` (it does not have to be four letters). `your_domain_like_for_example_anatomy` could be simply `anatomy`, and the license should be whatever your actual license is. An example can be found [here](https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/amphx.md), but you really only need to fill in the metadata mentioned here.

```
id: pcl
title: "Provisional Cell Ontology"
contact:
  email: davidos@ebi.ac.uk
  label: David Osumi-Sutherland
  email: rscheuermann@jcvi.org
  label: Richard Scheuermann
description: Cell types that are provisionally defined by experimental techniques such as single cell or single nucleus transcriptomics rather than a straightforward & coherent set of properties. 
domain: obophenotype
homepage: https://github.com/obophenotype/provisional_cell_ontology
products:
  - id: pcl.owl
  - id: pcl.obo
  - id: pcl.json
  - id: pcl-base.owl
  - id: pcl-base.obo
  - id: pcl-base.json
  - id: pcl-full.owl
  - id: pcl-full.obo
  - id: pcl-full.json
  - id: pcl-simple.owl
  - id: pcl-simple.obo
  - id: pcl-simple.json
dependencies:
  - id: pr
  - id: go
  - id: uberon 
  - id: ro
  - id: pato
  - id: ncbitaxon
  - id: bfo
  - id: cl
  - id: omo
  - id: nbo
  - id: chebi
  - id: so
tracker: https://github.com/obophenotype/provisional_cell_ontology/issues
license:
  url: http://creativecommons.org/licenses/by/4.0/
  label: CC-BY 4.0
usages:
  - user: https://biccn.org/
    description: This ontology will be used to annotate cell types in single cell transcriptomics data, with an initial focus on the brain. It is also used to drive search and navigation in a cell type data explorer web application. 
```

**Comment by shawntanzk** [comment]
@dosumis tagging to ping you

**Comment by lubianat** [comment]
@shawntanzk interesting proposal. 
Any comments on how definitions will be set? 
I imagine there won't be complete definitions in a rigorous sense (i.e. necessary and sufficient). 
How do you plan on handling that? I see: 
- https://github.com/obophenotype/provisional_cell_ontology/issues/11

But I am under the impression that issue is more about _scope_ than definitions per se.

**Comment by matentzn** [comment]
@shawntanzk thank you for you submission. I have updated your metadata according to our standards, please use that moving forward:

```
id: pcl
      mirror_from: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/pcl-base.owl
      title: "Provisional Cell Ontology"
      contact:
        email: davidos@ebi.ac.uk
        label: David Osumi-Sutherland
        github: dosumis
      description: Cell types that are provisionally defined by experimental techniques such as single cell or single nucleus transcriptomics rather than a straightforward & coherent set of properties. 
      domain: phenotype
      homepage: https://github.com/obophenotype/provisional_cell_ontology
      products:
        - id: pcl.owl
        - id: pcl.obo
        - id: pcl.json
        - id: pcl-base.owl
        - id: pcl-base.obo
        - id: pcl-base.json
        - id: pcl-full.owl
        - id: pcl-full.obo
        - id: pcl-full.json
        - id: pcl-simple.owl
        - id: pcl-simple.obo
        - id: pcl-simple.json
      dependencies:
        - id: pr
        - id: go
        - id: uberon 
        - id: ro
        - id: pato
        - id: ncbitaxon
        - id: bfo
        - id: cl
        - id: omo
        - id: nbo
        - id: chebi
        - id: so
      tracker: https://github.com/obophenotype/provisional_cell_ontology/issues
      license:
        url: http://creativecommons.org/licenses/by/4.0/
        label: CC BY 4.0
      usages:
        - user: https://biccn.org/
          description: This ontology will be used to annotate cell types in single cell transcriptomics data, with an initial focus on the brain. It is also used to drive search and navigation in a cell type data explorer web application. 
      repository: https://github.com/obophenotype/provisional_cell_ontology
      preferredPrefix: PCL
```

You can see your dashboard checks here:

https://obofoundry.org/obo-nor.github.io/dashboard/index.html

As per OBO guidelines no check may fail apart from usages. You don't fail any checks, so you are good to go! Impressive! (The warning on the license is a minor issue I have fixed for you in the above metadata, so no need to act on it).

Please, as per new guidelines:
- [ ] Confirm you have no namespace clash with [BioPortal](http://bioportal.bioontology.org/ontologies)
- [ ] Confirm you have no namespace clash with [bioregistry](https://bioregistry.io/)

We will assign a reviewer at our next operations call, and will come back with a decision 14 days after that. Rough timeline: end of January, hope that is ok.
