### ISSUE TITLE
ELO

### ISSUE THREAD

**Issue by Aymenchaalia** [OBOFoundry/OBOFoundry.github.io#1729]
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

## Ontology title
ELO (Ethnolingustic ontology)

## Requested ID space
ELO

## Ontology location
Tesla local server
http://tesla.pasteur.tn/elo/v1.0/index.html

## Contact person
Name: Aymen BEN CHAALIA
Email address: aymenbenchaalia1@gmail.com
GitHub username: Aymenchaalia

## Issue tracker

https://github.com/Aymenchaalia/ELO-Public-issue-trackers

## Ontology license

- [X ] CC0 (public domain)
- [ ] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
OWL

## What domain is the ontology intended to cover?

Ethnolinguistic, Genetics

## Related OBO Foundry ontologies
ontologies
None

## Intended use/related projects

H3Africa, H3ABioNet, DSI-AFRICA
The Human Heredity and Health in Africa (H3Africa) consortium facilitates fundamental
research into diseases on the African continent while also developing infrastructure,
resources, training, and ethical guidelines to support a sustainable African research enterprise
– led by African scientists, for the African people. H3Africa empowers African researchers to
be competitive in genomic sciences, establishes and nurtures effective collaborations among
African researchers on the African continent, and generates unique data that could be used to
improve both African and global health.
H3ABioNet aims to create a sustainable African Bioinformatics Network to support H3Africa
researchers through the development of bioinformatics capacity on the continent. H3ABioNet
will provide a framework for integration of and communication among all of the H3Africa
research and resource projects, as well as other sites in Africa that are carrying out
genomic/genetic research. The network will provide computational infrastructure and
hardware, human resources, tools and computational solutions for genomic and population-
based research, and communications among African researchers and other interested parties.

## Data source
Wikipedia
Glotog 
Ethnologue

## Additional comments or remarks
The ELO is employed to comprehensively classify African study participants in prospective
research studies. It can also be used to classify study participants of past studies, by mapping
participants using a language or ethnicity identifier or synonyms. It&#39;s a tool to annotate the
ethnicity of African individuals, and brings together knowledge accumulated about existing
populations with their genetic fingerprint in a standardized format. Researchers, physicians,

geneticists, anthropologists and any persons can use this ontology and take advantage of the
various ethnolingustic and genetic data available.

## OBO Foundry pre-registration checklist

To be considered for inclusion in the OBO Foundry, an ontology must meet certain requirements, as described in in [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration review checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md). To ensure you are aware of some of its key points, please review the checklist below.

You can either check a box by submitted the request first and then using the GitHub interface, or replacing the `- [ ]` by `- [X]` in the following.

- [X ] I have read an understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md) 
- [ X] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there was, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [ X] My ontology has a specific release file with a version IRI and a dc:license annotation, serialised in RDF/XML.
- [ X] I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, using the [IAO:0000115](http://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [ X] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [ X] For all relationship properties (Object and Data Property) I checked whether [RO](http://www.ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [ X] For the selection of appropriate annotation properties, I looked at [OMO](http://www.ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies. 
- [ X] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice.

## Metadata

Please fill in the following metadata record which will be used by the OBO Foundry website. Note that the values shown are just examples, for example `yourfourletterid` could be something like `aism`, `cohm`, `mondo` (it does not have to be four letters). `your_domain_like_for_example_anatomy` could be simply `anatomy`, and the license should be whatever your actual license is. An example can be found [here](https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/amphx.md), but you really only need to fill in the metadata mentioned here.

```
id: yourfourletterid
title: Ethnolingustic ontology
contact: Aymen BEN CHAALIA
  email: aymenbenchaalia1@gmail.com
  label: Aymen
description: Some one sentence description of your ontology.
domain: your_domain_like_for_example_anatomy
homepage: https://github.com/YOURORG/your_repo
products:
  - id: yourfourletterid.owl
  - id: yourfourletterid.obo
dependencies:
  - id: ro
  - id: otheroboontology
tracker: https://github.com/YOURORG/your_repo/issues
license:
  url: http://creativecommons.org/licenses/by/3.0/
  label: CC-BY
usages:
  - user: http://website.of.the.project.using.my.ontology.com
    description: A short description of how the project above is using my ontology
```

**Comment by cthoyt** [comment]
Hi @Aymenchaalia thanks for following up on your previous issue. Could you make a few improvements:

1. It seems the `Ontology title` also contains the information requested in the `Requested ID space` field, please split those up.
2. Can you provide actual links to the ontology artifacts? 
3. Public issue trackers, preferably on GitHub, are required for all OBO ontologies. Please add one.
4. Please add a link to the repository where this ontology is being maintained (again, using GitHub is the most useful way for an ontology to interface with the broader community, so this is HIGHLY suggested)
4. Would you please provide more context on the intended use/projects (H3Africa, H3ABioNet, DSI-AFRICA) for example, with links to these projects
5. Can you please write a description of what ELO is, what problems it solves, and what kinds of researchers would use it?

Please make all of these updates by editing the original issue text, **not in a reply comment** in order to keep this thread as clean as posisble

**Comment by cthoyt** [comment]
@Aymenchaalia I saw that you added me specifically to the private GitHub repository https://github.com/Aymenchaalia/ELO-Public-issue-trackers, but this is not sufficient - this tracker needs to be public. I would suggest looking at some of repositories in the rest of the OBO Foundry to see what kind of information they include (e.g., a license file, a README.md, a CONTRIBUTING.md file)

**Comment by Aymenchaalia** [comment]
Dear Charles,

Sorry for the late reply.
I added the README file and made the repository public.


 Regards,

**Comment by matentzn** [comment]
@Aymenchaalia 

Unfortunately, your ontology does not parse at all - can you make sure your ontology opens correctly with [ROBOT](https://robot.obolibrary.org/) or Protege? 

Also, we need you to update the metadata:

```
id: yourfourletterid
title: Ethnolingustic ontology
contact: Aymen BEN CHAALIA
  email: aymenbenchaalia1@gmail.com
  label: Aymen
description: Some one sentence description of your ontology.
domain: your_domain_like_for_example_anatomy
homepage: https://github.com/YOURORG/your_repo
products:
  - id: yourfourletterid.owl
  - id: yourfourletterid.obo
dependencies:
  - id: ro
  - id: otheroboontology
tracker: https://github.com/YOURORG/your_repo/issues
license:
  url: http://creativecommons.org/licenses/by/3.0/
  label: CC-BY
usages:
  - user: http://website.of.the.project.using.my.ontology.com
    description: A short description of how the project above is using my ontology
```

To be considered for review.
