### ISSUE TITLE
Bipolar Disorder Ontology

### ISSUE THREAD

**Issue by phwegner** [OBOFoundry/OBOFoundry.github.io#1811]
<a href="https://obofoundry.org/obo-nor.github.io/dashboard/bpdo/dashboard.html"><img src="https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2FOBOFoundry%2Fobo-nor.github.io%2Fmaster%2Fdashboard%2Fbpdo%2Fdashboard-qc-badge.json" /></a>

## Ontology title
Bipolar Disorder Ontology

## Requested ID space
BPDO

## Ontology location
https://github.com/SCAI-BIO/bipolar-disorder-ontology/blob/main/releases/1.0.0/BPDO.owl

## Contact person
Name: Alpha Tom Kodamullil
Email address: alpha.tom.kodamullil@scai.fraunhofer.de
GitHub username: akodamullil

## Issue tracker
https://github.com/SCAI-BIO/bipolar-disorder-ontology/issues
## Version Controlled Repository
https://github.com/SCAI-BIO/bipolar-disorder-ontology
## Ontology license

- [ ] CC0 (public domain)
- [X] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
.owl

## What domain is the ontology intended to cover?
Bipolar Disorder 

## Related OBO Foundry ontologies
DOID, BFO

## Intended use/related projects
A disease ontology to classify Bipolar Disorder and calculate semantic similarities in the domain of Bipolar Disorder, Annotation of medical texts

## Data source
Several sources from domain experts assembled by Fraunhofer SCAI and Computational Biomodels (CBM)

## OBO Foundry pre-registration checklist
Created by the team for applied semantics at Fraunhofer SCAI
To be considered for inclusion in the OBO Foundry, an ontology must meet certain requirements, as described in in [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration review checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md). To ensure you are aware of some of its key points, please review the checklist below.

You can either check a box by submitted the request first and then using the GitHub interface, or replacing the `- [ ]` by `- [X]` in the following.

- [X] I have read and understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md) 
- [X] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there was, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [X] My ontology has a specific release file with a version IRI and a dc:license annotation, serialised in RDF/XML.
- [X] I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, using the [IAO:0000115](http://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [X] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [X] For all relationship properties (Object and Data Property) I checked whether [RO](http://www.ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [X] For the selection of appropriate annotation properties, I looked at [OMO](http://www.ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies. 
- [X] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice.
- [X] The requested ID space does not conflict with another ID space found in other registries such as BioPortal and the Bioregistry, see [here](https://obofoundry.org/id-policy) for a complete list.

## Metadata

Please fill in the following metadata record which will be used by the OBO Foundry website. Note that the values shown are just examples, for example `yourfourletterid` could be something like `aism`, `cohm`, `mondo` (it does not have to be four letters). `your_domain_like_for_example_anatomy` could be simply `anatomy`, and the license should be whatever your actual license is. An example can be found [here](https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/amphx.md), but you really only need to fill in the metadata mentioned here.

```
id: BPDO
title: Bipolar Disorder Ontology
contact:
  email: alpha.tom.kodamullil@scai.fraunhofer.de
  label: Alpha Tom Kodamullil
description: The Bipolar Disorder ontology includes bipolar disorder-related concepts, terms and related synonyms, collected from wide variety of sources such us publications and websites.
domain: Mental Disorder
homepage: https://github.com/SCAI-BIO/bipolar-disorder-ontology
products:
  - id: BPDO.owl
  - 
dependencies:
  - id: BFO
tracker: https://github.com/SCAI-BIO/bipolar-disorder-ontology/issues
license:
  url: http://creativecommons.org/licenses/by/4.0/
  label: CC-BY
usages:
  - user: - 
    description: - 
```
