### ISSUE TITLE
add OBO ops roles to the website

### ISSUE THREAD

**Issue by nicolevasilevsky** [OBOFoundry/OBOFoundry.github.io#2141]
see slack thread
https://obo-communitygroup.slack.com/archives/C01B6MQCDLN/p1664967782409519

**Comment by cthoyt** [comment]
I think it would make sense to have these either 
1. auto-generated from a YAML configuration file
2. layout + markdown that inherits from the layout, similar to how the principles and ontologies are shown

**Comment by nicolevasilevsky** [comment]
Ok! I'm not sure how to do that. Would you like to get it started and then I can fill in the rest?

**Comment by cthoyt** [comment]
Make a YAML file in `_data/roles.yml` and add in the following:

```yaml
- name: Registry Metadata Steward
  commitment: 2-4 hours per month
  requirements:
    - Love for metadata
    - basic python
    - community mindset
  description: |
    You are responsible for shepherding our registry
    metadata according to our principles and SOPs, merge changes and generally
    protect and guard them. This involves also facilitating the implementation of QC
    checks.
- name: OBO NOR Dashboard maintainer
  commitment: 2-6 hours per month
  requirements:
    - Basic knowledge of dashboard
    - Social skills are a nice to have
    - Infinite patience also helpful
  description: |
    You will be responsible for registering new ontologies at the OBO dashboard and helping their
    owners pass them.
```
