### ISSUE TITLE
Create a page showing all publications about OBO papers (and any papers that cite them)

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#220]
It should be easy to take the publications field, e.g.

```
publications:
  - id: http://www.ncbi.nlm.nih.gov/pubmed/22293552
    title: "Uberon, an integrative multi-species anatomy ontology"
  - id: http://www.ncbi.nlm.nih.gov/pubmed/25009735
    title: "Unification of multi-species vertebrate anatomy ontologies for comparative biology in Uberon"
```

aggregate these into a single object in _config.yml and have a page that shows all publications.

Could also do a scholar/ncbi query that shows all publications citing OBO ones

We may need a separate metadata field for papers about the OBO Foundry itself - e.g. the NBT one but also associated tooling papers
