### ISSUE TITLE
Add metadata for people

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#24]
Each person (OBO team, or possibly also ontology developers) could have an entry in the config.yml file

E.g.

```
team:
  - name: Chris Mungall
    orcid: ORCIDURL
    github: cmungall
    roles: [twg,...]
```

Or alternatively, one md per person (that can be collected same way as ontologies)

This would be easy to render as html in jekyll

The YAML would have a json-ld context allowing direct translation to RDF
