### ISSUE TITLE
Add a metadata field that links to annotations

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#2527]
Here annotations refers to text mining corpora like CRAFT, biolark, as well as standard gene associations such as those curated by GOC/HPOA/Monarch.

We should make it easier for ontology users to navigate from an ontology to annotations

For text mining corpora in particular my experience has been that it's painful to navigate lots of implicit information about where to download the corpora, what version of subset of the ontology was used, what curation practice was used etc.

**Comment by matentzn** [comment]
Something like this perhaps?

```
annotated_datasets:
   - id: hpoa
      url: http://purl.obolibrary.org/obo/hp/genes_to_phenotype.txt
      documentation: https://hpo.jax.org/app/data/annotations
```
