### ISSUE TITLE
test

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#889]
# New Ontology Request

foobar

Use this form for registering a new ontology with OBO. Consult the FAQ on http://obofoundry.org with any questions. Please fill in the values for all required (\*) fields to the best of your abilities.

Please note that joining the OBO Foundry includes a commitment to follow Foundry principles. In addition to obtaining basic information about your ontology, the questions below are meant to highlight these principles, provide our expectations, and assess commitment for joining the OBO Foundry. The answers also help us identify the right person to review your PURL request.

PURL Request documentation: http://www.obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html

Please review the OBO Foundry Principles before proceeding with this submission. The OBO Foundry Principles can be found at: http://obofoundry.org/principles/fp-000-summary.html

## Ontology title \*
Concise title of your ontology (e.g, "Gene Ontology")

foobar

## Requested ID space \*
Prefix of ontology in lowercase (e.g., go, uberon, chebi, cl). The OBO Foundry ID policy is described at http://obofoundry.org/id-policy.html

## Ontology location \*
Home page or URL of ontology. This can be a GitHub URL.

## Contact person \*
Name, email address, and GitHub username of contact person. The OBO Foundry policy on contact person is described at http://obofoundry.org/principles/fp-011-locus-of-authority.html.

## Issue tracker \*
URL for submitting and responding to suggestions, requests, etc. (e.g., https://github.com/geneontology/go-ontology/issues/).

## Ontology license \*
Current license. Note that the OBO Foundry accepts CC0 or CC-BY. The OBO Foundry license policy is described at http://www.obofoundry.org/principles/fp-001-open.html.

- [ ] CC0 (public domain)
- [ ] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats \*

Note that OWL-RDF/XML is the only required format. The OBO Foundry format policy is described at http://obofoundry.org/principles/fp-002-format.html.

## What domain is the ontology intended to cover? \*

For example, the GO covers the processes, functions and cellular locations of gene products. The OBO Foundry policy on scope of an ontology is described at http://obofoundry.org/principles/fp-005-delineated-content.html.

## Related OBO Foundry ontologies \*

What other ontologies are you aware of that intersect with your domain, and what are your plans for collaborating with them? The OBO Foundry policy on collaboration is described at http://obofoundry.org/principles/fp-010-collaboration.html.

## Intended use/related projects \*

Is your ontology serving the need of one or more specific projects? If so, please describe them. The OBO Foundry policy on documented users is described at http://obofoundry.org/principles/fp-009-users.html.

## Data source \*

Which resources, if any, were used to generate the ontology? E.g., NCBITaxon was created from the NCBI taxonomy resource; the Protein Ontology uses, in part, UniProtKB.

## Additional comments or remarks

Another other significant information that you'd like to let us know.

```
---
layout: ontology_detail
id: ONTOLOGY IDSPACE (LOWERCASE) E.g. obi
title: FULL NAME E.g. Ontology of Biomedical Investigations
description: BRIEF ONE SENTENCE DESCRIPTION OF YOUR ONTOLOGY
homepage: URL
contact:
  label: CONTACT NAME
  email: CONTACT EMAIL
license:
  label: CC-BY 4.0
  url: http://creativecommons.org/licenses/by/4.0/
tracker: TRACKER URL
source_url: URL THAT RESOLVES TO OWL FOR YOUR ONTOLOGY
products:
  - id: IDSPACE.owl
    title: IDSPACE
domain: E.g. OBI is an integrated ontology for the description of life-science and clinical investigations
related: I.e. what other ontologies are you aware of that intersect with your domain, if any?
use: Is your ontology serving the need of one or more specific projects? If so, please describe them.
upstreams: Which resources, if any, were used to generate the ontology (e.g., NCBITaxon was created from the NCBI taxonomy resource; the Protein Ontology uses, in part, UniProtKB).
notes: ANY ADDITIONAL NOTES
activity_status: active
---

ENTER A DETAILED DESCRIPTION OF YOUR ONTOLOGY HERE
You can use Markdown format
```
